trigger:
  - main

strategy:
  matrix:
    python_version:
      - "3.8"
      - "3.9"
      - "3.10"
    os:
      - windows-2019
      - ubuntu-20.04
      - macOS-11.0

pool:
  vmImage: $(os)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python_version)"
      addToPath: true

  - script: |
      python --version
    displayName: "Print Python version"
